# Generated by Django 5.0.3 on 2024-04-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='course_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد دوره مربی'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شمماره تماس'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='student_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد دانشجوی مربی'),
        ),
    ]
