# Generated by Django 5.0.3 on 2024-04-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_coach_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='user',
        ),
    ]
