# Generated by Django 5.0.3 on 2024-05-18 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_remove_coach_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'مربی ', 'verbose_name_plural': 'مربی ها'},
        ),
    ]
