# Generated by Django 5.0.3 on 2024-05-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_alter_coach_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='like',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد لایک مربی'),
        ),
    ]
