# Generated by Django 5.0.3 on 2024-04-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=50, null=True, verbose_name='عنوان دوره')),
                ('discription', models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیحات دوره')),
                ('number_cousre', models.IntegerField(blank=True, null=True, verbose_name='تعداد دوره')),
                ('time_course', models.DateTimeField(blank=True, null=True, verbose_name='مدت زمان دوره')),
                ('price_course', models.IntegerField(blank=True, null=True, verbose_name='هزینه دوره ')),
                ('image_course', models.ImageField(blank=True, null=True, upload_to='image_course', verbose_name='عکس دوره ')),
            ],
        ),
    ]
