# Generated by Django 5.0.3 on 2024-04-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_course',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدت زمان دوره'),
        ),
    ]
