# Generated by Django 5.0.3 on 2024-04-23 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_time_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, null=True, verbose_name='دسته بندی درور ها ')),
                ('discription', models.TextField(blank=True, max_length=100, null=True, verbose_name='توضیحات دسته بندی ها ')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='استاده دوره '),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, to='course.category', verbose_name='دسته بندی دور ه '),
        ),
    ]
