# Generated by Django 5.0.3 on 2024-04-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_category_course_teacher_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='number_cousre',
        ),
    ]
