# Generated by Django 5.0.3 on 2024-04-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_like_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='numbers_members',
            field=models.IntegerField(blank=True, null=True, verbose_name=' تعداد دانسجویان دروه '),
        ),
    ]
