# Generated by Django 5.0.3 on 2024-04-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_like_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.ManyToManyField(blank=True, to='course.category', verbose_name='دسته بندی دور ه '),
        ),
    ]
