# Generated by Django 5.0.3 on 2024-04-23 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('image_user', models.ImageField(blank=True, null=True, upload_to='image_user', verbose_name='عکسک کاربر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اطلاعات کاربر')),
            ],
        ),
    ]
