# Generated by Django 5.0.3 on 2024-05-18 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل کاربر ها '},
        ),
    ]
