# Generated by Django 5.0.3 on 2024-04-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان وبلاگ')),
                ('discription', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات وبلاگ')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار وبلاگ')),
                ('type', models.TextField(blank=True, null=True, verbose_name='نوع وبلاگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='veblog_image', verbose_name='عکس وبلاگ')),
            ],
        ),
    ]
