# Generated by Django 5.0.3 on 2024-04-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veblog', '0004_alter_veblog_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='veblog',
            old_name='date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='veblog',
            name='type',
        ),
        migrations.AddField(
            model_name='veblog',
            name='type',
            field=models.ManyToManyField(to='veblog.category'),
        ),
    ]
