# Generated by Django 5.0.3 on 2024-04-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veblog', '0005_category_rename_date_veblog_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veblog',
            name='type',
            field=models.ManyToManyField(to='veblog.category', verbose_name=' دسته بندی ها'),
        ),
    ]
