# Generated by Django 5.0.3 on 2024-04-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veblog', '0007_alter_veblog_options_alter_veblog_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veblog',
            options={'ordering': ['updated']},
        ),
        migrations.AddField(
            model_name='veblog',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ به روز رسانی وبلاگ'),
        ),
    ]
