# Generated by Django 5.0.3 on 2024-04-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veblog', '0008_alter_veblog_options_veblog_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veblog',
            options={},
        ),
    ]
