# Generated by Django 5.0.3 on 2024-04-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veblog', '0010_alter_category_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datee', models.DateTimeField()),
            ],
        ),
    ]
