# Generated by Django 5.0.3 on 2024-04-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veblog', '0011_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='datee',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
