# Generated by Django 5.0.3 on 2024-04-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veblog', '0012_alter_test_datee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
