# Generated by Django 5.0.3 on 2024-04-30 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veblog', '0013_delete_test'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300, null=True, verbose_name='متن کامنت')),
                ('created_comment', models.DateTimeField(auto_now_add=True, verbose_name='زمان کامنت')),
                ('reply_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veblog.comment', verbose_name='پاسخ به کامنت ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم کاربر')),
                ('vrblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veblog.veblog', verbose_name='کامنت برای مقاله')),
            ],
        ),
    ]
