# Generated by Django 5.0.3 on 2024-04-30 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veblog', '0014_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='veblog.comment', verbose_name='پاسخ به کامنت '),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vrblog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veblog', to='veblog.veblog', verbose_name='کامنت برای مقاله'),
        ),
    ]
