# Generated by Django 5.0.3 on 2024-04-30 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veblog', '0015_alter_comment_reply_comment_alter_comment_vrblog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='اسم کاربر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vrblog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='veblog.veblog', verbose_name='کامنت برای مقاله'),
        ),
    ]
