# Generated by Django 5.0.3 on 2024-05-18 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veblog', '0016_alter_comment_user_alter_comment_vrblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها '},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='veblog',
            options={'verbose_name': 'وبلاگ', 'verbose_name_plural': 'وبلاگ ها '},
        ),
    ]
