# Generated by Django 5.0.3 on 2024-04-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان پیام')),
                ('discription', models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات پیام ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل کاربر')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تماس')),
            ],
        ),
    ]
