# Generated by Django 5.0.3 on 2024-05-18 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0002_alter_massage_email_alter_massage_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massage',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها '},
        ),
    ]
