# Generated by Django 5.0.3 on 2024-04-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم محصول موجو د ')),
                ('price_product', models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='قیمت واحد محصول')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='نام و نام خانوادگی مشتری')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='شماره تماس مشتری')),
                ('number_product', models.IntegerField(null=True, verbose_name='تعداد محصول خرید کرده ')),
                ('all_costs', models.DecimalField(decimal_places=3, max_digits=3, null=True, verbose_name='کل یدهی مشتری')),
                ('date', models.DateTimeField(auto_now=True, null=True, verbose_name='آخرین زمان خرید مشتری')),
                ('product', models.ManyToManyField(to='hesabdari.product')),
            ],
        ),
    ]
