# Generated by Django 5.0.3 on 2024-04-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabdari', '0002_alter_product_price_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_product',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='قیمت واحد محصول'),
        ),
    ]
