# Generated by Django 5.0.3 on 2024-04-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabdari', '0006_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='all_costs',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='کل یدهی مشتری'),
        ),
    ]
