# Generated by Django 5.0.3 on 2024-04-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hesabdari', '0009_customer_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product_number',
        ),
    ]
