# Generated by Django 5.0.3 on 2024-05-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabdari', '0012_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_product',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت واحد محصول'),
        ),
    ]
