# Generated by Django 5.0.3 on 2024-05-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hesabdari', '0014_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='percent_price',
        ),
    ]
