# Generated by Django 5.0.3 on 2024-05-14 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabdari', '0015_rename_size_product_percent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percent_price',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف محصول'),
        ),
    ]
