# Generated by Django 5.0.3 on 2024-05-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabdari', '0018_alter_customer_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='all_costs',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='کل یدهی مشتری'),
        ),
    ]
